# Exercise

In [1]:
import numpy as np

In [2]:
import torch

#### Set the random seed

In [4]:
np.random.seed(42)

In [5]:
torch.seed = 42

#### Create a numpy arr contains 6 random integers

In [6]:
arr = np.random.randint(low=0, high=5, size=6)

In [7]:
arr

array([3, 4, 2, 4, 4, 1])

#### Create a tensor "x" from the array above

In [8]:
x = torch.tensor(arr, dtype=torch.float32)

In [9]:
x

tensor([3., 4., 2., 4., 4., 1.])

In [10]:
x = x.type(dtype=torch.int64)

In [11]:
x.dtype

torch.int64

#### Reshape x into a 3*2 tensor

In [13]:
x = x.reshape(3,2)

In [14]:
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

#### Return the right-hand column of tensor x

In [16]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

#### Square values of x

In [17]:
x.square()

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

tensor([[0.0938, 0.1250],
        [0.0625, 0.1250],
        [0.1250, 0.0312]])

#### Matrix-multiplied

In [21]:
y = torch.randint(low=0, high=5, size=(2,3))

In [22]:
y

tensor([[4, 4, 3],
        [2, 3, 1]])

In [23]:
y.shape

torch.Size([2, 3])

In [24]:
x.shape

torch.Size([3, 2])

In [25]:
torch.mm(x,y)

tensor([[20, 24, 13],
        [16, 20, 10],
        [18, 19, 13]])

In [26]:
torch.mm(y,x)

tensor([[32, 35],
        [16, 21]])

In [27]:
x.mm(y)

tensor([[20, 24, 13],
        [16, 20, 10],
        [18, 19, 13]])

In [28]:
y.mm(x)

tensor([[32, 35],
        [16, 21]])

In [32]:
torch.matmul(x,y)

tensor([[20, 24, 13],
        [16, 20, 10],
        [18, 19, 13]])

In [ ]:
Well Don