# Tensors

In [1]:
import numpy as np

In [2]:
import torch

In [4]:
np_arr = np.array([1,2,3,4,5])

In [8]:
torch.tensor(np_arr).dtype

torch.int32

In [7]:
torch.Tensor(np_arr).dtype

torch.float32

In [9]:
torch.FloatTensor(np_arr)

tensor([1., 2., 3., 4., 5.])

#### Tensors from scratch

In [12]:
torch.empty(2,2)

tensor([[9.1477e-41, 1.0194e-38],
        [1.2107e-42, 0.0000e+00]])

In [13]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
torch.zeros(4,3, dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [24]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(0,10).reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [29]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [30]:
my_tensor = torch.tensor([1,2,3])

In [32]:
my_tensor.dtype

torch.int64

In [35]:
my_tensor = my_tensor.type(torch.int32)

In [36]:
my_tensor.dtype

torch.int32

#### Randoms

In [37]:
torch.rand(3,4)

tensor([[0.7455, 0.5439, 0.6261, 0.5728],
        [0.3217, 0.3201, 0.2159, 0.4546],
        [0.3763, 0.5424, 0.6668, 0.4789]])

In [39]:
torch.randn(3,6)

tensor([[-0.3693,  0.7226, -2.2026,  0.8747, -0.0496,  1.5147],
        [-0.2718,  0.2231,  0.3497,  1.1737,  0.3739,  0.5086],
        [-0.0631,  2.5862, -1.4015,  0.7886, -0.7975, -0.0846]])

In [43]:
torch.randint(low=0, high=20, size=(5,5))

tensor([[10,  6,  8,  2, 17],
        [ 2,  9, 13, 10,  7],
        [17,  1,  1,  0, 12],
        [ 9,  5,  2,  4,  7],
        [13,  0, 19, 19,  0]])

In [44]:
x = torch.zeros(2,5)

In [45]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [46]:
torch.rand_like(x)

tensor([[0.8132, 0.6179, 0.3046, 0.7445, 0.3191],
        [0.6618, 0.2100, 0.8615, 0.3280, 0.0991]])

In [48]:
torch.randn_like(x)

tensor([[-0.3350, -1.0898, -0.5004,  0.1419, -1.3089],
        [ 0.7346, -0.5507,  1.1056,  0.8565, -1.9577]])

In [49]:
torch.randint_like(x, low=0, high=11)

tensor([[0., 7., 8., 8., 9.],
        [9., 5., 7., 5., 5.]])

In [56]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [57]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])