In [1]:
import numpy as np

In [2]:
import torch

In [3]:
x = torch.arange(6).reshape(3,2)

In [4]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
x[1,1]

tensor(3)

In [6]:
x[1]

tensor([2, 3])

In [7]:
x[:,1]

tensor([1, 3, 5])

In [8]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [9]:
x = torch.arange(10)

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = torch.arange(10)

In [14]:
x.shape

torch.Size([10])

In [15]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
z = x.view(2,5)

In [17]:
x[0] = 123

In [18]:
x

tensor([123,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
z

tensor([[123,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [20]:
x = torch.arange(10)

In [21]:
x.shape

torch.Size([10])

In [22]:
# Infer what the 2nd dimension is  
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#### Main operations

In [24]:
a = torch.tensor([1.,2.,3.])

In [25]:
b = torch.tensor([4.,5.,6.])

In [26]:
a.dtype

torch.float32

In [27]:
b.dtype

torch.float32

In [28]:
a + b

tensor([5., 7., 9.])

In [29]:
torch.add(a,b)

tensor([5., 7., 9.])

In [30]:
a.mul(b)

tensor([ 4., 10., 18.])

In [31]:
a

tensor([1., 2., 3.])

In [32]:
# a = a * b
a.mul_(b)

tensor([ 4., 10., 18.])

In [33]:
a

tensor([ 4., 10., 18.])

In [36]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6])

In [35]:
a

tensor([1., 2., 3.])

In [37]:
b

tensor([4., 5., 6.])

In [38]:
a * b

tensor([ 4., 10., 18.])

#### dot product

In [39]:
a.mul(b)

tensor([ 4., 10., 18.])

In [40]:
a.dot(b)

tensor(32.)

In [41]:
a = torch.tensor([[0,2,4],
                  [1,3,5]])

In [42]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [43]:
a.shape

torch.Size([2, 3])

In [44]:
b.shape

torch.Size([3, 2])

In [45]:
torch.matmul(a,b)

tensor([[56, 62],
        [80, 89]])

In [46]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [47]:
a.matmul(b)

tensor([[56, 62],
        [80, 89]])

In [48]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [51]:
x = torch.tensor([2.,3.,4.,5.])

In [52]:
x.norm()

tensor(7.3485)

In [53]:
x.numel()

4

In [54]:
len(x)

4

In [55]:
len(a)

2

In [56]:
a.size()

torch.Size([2, 3])

In [57]:
a.numel()

6