# Tensor Basics

In [1]:
import numpy as np

In [2]:
import torch

In [3]:
torch.version

<module 'torch.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch\\version.py'>

In [4]:
torch.__version__

'1.13.1'

In [5]:
arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [9]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [10]:
x = torch.from_numpy(arr)

In [11]:
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [12]:
type(x)

torch.Tensor

In [16]:
x.size()

torch.Size([4])

In [17]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [18]:
x.dtype

torch.int32

In [19]:
matrix = np.arange(0.0,12.0)

In [23]:
matrix = matrix.reshape(3,4)

In [24]:
matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [25]:
torch.as_tensor(matrix)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [26]:
torch.from_numpy(matrix)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [27]:
my_arr = np.arange(0,10)

In [28]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_tensor = torch.tensor(my_arr)

In [31]:
my_other_tensor = torch.from_numpy(my_arr)

In [32]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [33]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [34]:
my_arr[0] = 99999

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [36]:
my_other_tensor

tensor([99999,     1,     2,     3,     4,     5,     6,     7,     8,     9],
       dtype=torch.int32)