# Tensors

In [1]:
import numpy as np

In [2]:
import torch

In [4]:
np_arr = np.array([1,2,3,4,5])

In [8]:
torch.tensor(np_arr).dtype

torch.int32

In [7]:
torch.Tensor(np_arr).dtype

torch.float32

In [9]:
torch.FloatTensor(np_arr)

tensor([1., 2., 3., 4., 5.])

#### Tensors from scratch

In [12]:
torch.empty(2,2)

tensor([[9.1477e-41, 1.0194e-38],
        [1.2107e-42, 0.0000e+00]])

In [13]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
torch.zeros(4,3, dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [24]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(0,10).reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [29]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [30]:
my_tensor = torch.tensor([1,2,3])

In [32]:
my_tensor.dtype

torch.int64

In [35]:
my_tensor = my_tensor.type(torch.int32)

In [36]:
my_tensor.dtype

torch.int32