# Tensor Basics

In [1]:
import numpy as np

In [2]:
import torch

In [3]:
torch.version

<module 'torch.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch\\version.py'>

In [4]:
torch.__version__

'1.13.1'

In [5]:
arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [9]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [10]:
x = torch.from_numpy(arr)

In [11]:
x

tensor([1, 2, 3, 4], dtype=torch.int32)

In [12]:
type(x)

torch.Tensor

In [16]:
x.size()

torch.Size([4])

In [ ]:
torch.as_tensor(arr)