In [1]:
import numpy as np

In [2]:
import torch

In [3]:
x = torch.arange(6).reshape(3,2)

In [4]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
x[1,1]

tensor(3)

In [6]:
x[1]

tensor([2, 3])

In [7]:
x[:,1]

tensor([1, 3, 5])

In [8]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [9]:
x = torch.arange(10)

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = torch.arange(10)

In [14]:
x.shape

torch.Size([10])

In [15]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
z = x.view(2,5)

In [17]:
x[0] = 123

In [18]:
x

tensor([123,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
z

tensor([[123,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [20]:
x = torch.arange(10)

In [21]:
x.shape

torch.Size([10])

In [22]:
# Infer what the 2nd dimension is  
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

#### Main operations

In [38]:
a = torch.tensor([1.,2.,3.])

In [39]:
b = torch.tensor([4.,5.,6.])

In [28]:
a.dtype

torch.float32

In [29]:
b.dtype

torch.float32

In [30]:
a + b

tensor([5., 7., 9.])

In [31]:
torch.add(a,b)

tensor([5., 7., 9.])

In [32]:
a.mul(b)

tensor([ 4., 10., 18.])

In [33]:
a

tensor([1., 2., 3.])

In [40]:
# a = a * b
a.mul_(b)

tensor([ 4., 10., 18.])

In [41]:
a

tensor([ 4., 10., 18.])