In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4]

In [3]:
type(mylist)

list

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [9]:
arr.T

array([1, 2, 3, 4])

In [16]:
matrix = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]], dtype=np.int32)

In [17]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
matrix.shape

(3, 4)

In [23]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros(5, dtype=np.int16)

array([0, 0, 0, 0, 0], dtype=int16)

In [27]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

In [29]:
np.ones(shape=(3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.zeros(shape=(4,3)) + 32

array([[32., 32., 32.],
       [32., 32., 32.],
       [32., 32., 32.],
       [32., 32., 32.]])

In [32]:
[1,2,3,4,5] + 12

TypeError: can only concatenate list (not "int") to list

In [33]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [34]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])