# Index Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[11]

IndexError: index 11 is out of bounds for axis 0 with size 11

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [10]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_array = arr[0:4]

In [17]:
slice_of_array

array([0, 1, 2, 3])

In [18]:
slice_of_array[:] = 50

In [19]:
slice_of_array

array([50, 50, 50, 50])

In [20]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy[:] = 100000

In [23]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
       100000, 100000, 100000])

In [25]:
arr_2d = np.array([[5,10,15], [20,25,35], [35,40,45]])

In [26]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d.reshape(3,-1)

array([[ 5, 10, 15],
       [20, 25, 35],
       [35, 40, 45]])

In [28]:
arr_2d[1]

array([20, 25, 35])

In [29]:
arr_2d[1][1]

25

In [30]:
arr_2d[1,1]

25

In [31]:
arr_2d[2][2]

45

In [32]:
arr_2d[2,2]

45

In [33]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 35]])

In [34]:
arr = np.arange(1,11)

In [35]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 3

In [37]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])