# Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

#### Broadcasting

In [3]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [4]:
arr / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [6]:
(arr + 2) / 10

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr/0

C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [9]:
arr[0]/0

C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\2201256031.py:1: RuntimeWarning: invalid value encountered in long_scalars
  arr[0]/0


nan

In [11]:
arr[1] / 0

C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\389795143.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  arr[1] / 0


inf

#### Universals

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sqrt(arr).sum()

19.30600052603572

In [14]:
np.log(arr)

C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.log(arr)

C:\Users\IT Center\AppData\Local\Temp\ipykernel_7264\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
np.sum(arr)

45

In [19]:
np.max(arr)

9

In [20]:
np.min(arr)

0

In [23]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])

In [24]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr_2d.shape

(2, 4)

In [26]:
np.sum(arr_2d)

36

In [27]:
np.sum(arr_2d, axis=0)

array([ 6,  8, 10, 12])

In [28]:
np.sum(arr_2d, axis=1)

array([10, 26])