# Randoms

In [1]:
import numpy as np

In [2]:
np.random.rand()

0.12051877159121704

In [3]:
np.random.rand(5,5)

array([[0.3727946 , 0.26613506, 0.12728436, 0.16858988, 0.42089294],
       [0.89691099, 0.73053878, 0.47408358, 0.75108498, 0.07467363],
       [0.19871016, 0.58704075, 0.204891  , 0.75363218, 0.62026851],
       [0.64049306, 0.06910164, 0.73509705, 0.19733756, 0.99145229],
       [0.48258913, 0.95438105, 0.82377113, 0.7272979 , 0.3661158 ]])

In [4]:
np.random.rand(4)

array([0.59447004, 0.90019726, 0.64721887, 0.43333505])

In [5]:
np.random.randn(1)

array([-0.08878222])

In [6]:
np.random.randn(4,4)

array([[ 1.09366182,  0.17117554, -0.18016873, -0.59057226],
       [-0.23651159,  0.37708667, -0.71700333,  0.34756114],
       [-0.43562586,  0.2723597 , -0.04585905, -0.00639557],
       [-0.45777006, -0.40741409, -0.69023668, -0.6243134 ]])

In [7]:
np.random.randint(1, 100)

24

In [8]:
np.random.randint(1,100,20)

array([55, 84, 24, 79, 25, 70, 44, 38, 66, 89, 10, 51, 94, 62, 76, 87, 85,
       74, 41, 27])

In [9]:
np.random.seed(42)

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [10]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [11]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [12]:
arr = np.arange(25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
ranarr = np.random.randint(0,50,10)

In [15]:
ranarr

array([43, 29, 37,  1, 20, 32, 11, 21, 43, 24])

In [16]:
arr.shape

(25,)

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr_new = arr.reshape(1,-1)

In [19]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [20]:
arr_new.shape

(1, 25)

In [21]:
arr_new.argmax()

24

In [22]:
arr_new.argmin()

0